### ISSUE TITLE
Role definitions to be synchronized with DSSC

### ISSUE THREAD

**Issue by turpema** [International-Data-Spaces-Association/IDSA-Rulebook#19]
Some key roles, for example Data Holder, are not mentioned in the role descriptions. Needs to be synchronized with DSSC documents, including DSSC Glossary definitions.

**Comment by ssteinbuss** [comment]
The IDSA Rulebook describes some role models in the section [Guiding Principles](https://docs.internationaldataspaces.org/ids-knowledgebase/v/idsa-rulebook/idsa-rulebook/2_guiding_principles#role-models). 
We could add the definitions from the Glossary section ["Legal definitions regarding European data economy concepts"](https://dssc.eu/space/BPE/179175433/Data+Spaces+Blueprint+%7C+Version+0.5+%7C+September+2023), at least:

* Data holder
* Data recipient (DA)
* Data user
* Data intermediation service
* Data subject

This should also include a mapping of which of those roles are considered to be a participant in a data space and which are not considered to be a participant in a data space.

**Comment by ssteinbuss** [comment]
The Data space governance framework in the DSSC Blueprint is similar to the membership policies in the section on [policies](https://docs.internationaldataspaces.org/ids-knowledgebase/v/idsa-rulebook/idsa-rulebook/3_functional_requirements#policies). This also holds true for the "Policies and rules" in the section on [creating a data space](https://docs.internationaldataspaces.org/ids-knowledgebase/v/idsa-rulebook/idsa-rulebook/3_functional_requirements#creating-a-data-space). Should we align this with the Blueprint?

**Comment by ssteinbuss** [comment]
Further roles to be discussed in this context are from DSSC Blueprint section 4.2:

* Transaction participant
* Data space governance authority
* Data rights holder
* Data provider
* Data recipient

**Comment by ssteinbuss** [comment]
In general, the IDSA Rulebook lacks of a clear definition of a participant and the subsequent sub-roles. This should be included.

**Comment by ssteinbuss** [comment]
IDSA Rulebook does not describe in detail ecosystem service like explained in section 4.5 in the DSSC Blueprint. We might want to update IDSA Rulebook section on[optional functions](https://docs.internationaldataspaces.org/ids-knowledgebase/v/idsa-rulebook/idsa-rulebook/3_functional_requirements#optional-functions).

**Comment by ssteinbuss** [comment]
DSSC Blueprint Glossary has  in section 4.8 Data Policies and Contracts some definitions, which should be aligned with the IDSA [Rulebook section on Policies](https://docs.internationaldataspaces.org/ids-knowledgebase/v/idsa-rulebook/idsa-rulebook/3_functional_requirements#policies).

**Comment by ssteinbuss** [comment]
DSSC Blueprint Glossary in section 4.9. on identity and Trust should be aligned with our definitions in ["Establising Trust"](https://docs.internationaldataspaces.org/ids-knowledgebase/v/idsa-rulebook/idsa-rulebook/3_functional_requirements#establishing-trust)

**Comment by viivilahteenoja** [comment]
For reference, my work-in-progress glossary harmonisation exercise can be viewed here: https://airtable.com/app0PIxiDKt2XocA2/shrR0aceTswrZDmxN

**Comment by turpema** [comment]
Another term to be synced is "Data space authority" in IDSA Rulebook vs. "Data space governance authority" in DSSC Rulebook 2.0

**Comment by ssteinbuss** [comment]
> Another term to be synced is "Data space authority" in IDSA Rulebook vs. "Data space governance authority" in DSSC Glossary 2.0

We also need to update the figures accordingly.

**Comment by ssteinbuss** [comment]
This is already implemented
