### ISSUE TITLE
Update all References to the Rulebook on IDSA properties

### ISSUE THREAD

**Issue by PeterKoen-MSFT** [International-Data-Spaces-Association/IDSA-Rulebook#33]
The public website is still pointing to the Rulebook 1.0: https://internationaldataspaces.org/publications/white-papers/

We need to update all pointers to the rulebook to be in sync with the current version

**Comment by ssteinbuss** [comment]
already fixed here https://internationaldataspaces.org/publications/most-important-documents/ ,

Will update the IDSA homepage.

**Comment by ssteinbuss** [comment]
fixed on the IDSA Homepage. Will close the issue. Thx @PeterKoen-MSFT

**Comment by PeterKoen-MSFT** [comment]
Sorry, to reopen this issue: to avoid confusion, can we move documents that are not current to an archive section? Right now it looks like the current rulebook is competing with v1.0.

**Comment by ssteinbuss** [comment]
Then let's keep the issue open, we do not have a deprecated documents section on the IDSA Homepage. I think this needs to be established in the next few days.

**Comment by anilturkmayali** [comment]
After having checked the sections of IDSA website that are referring to IDSA Rulebook, it seems that the problem has been resolved. 

- [White Papers](https://internationaldataspaces.org/publications/white-papers/) 
- [Most Important Documents](https://internationaldataspaces.org/publications/most-important-documents/)
