### ISSUE TITLE
Add a section on Interoperability aspects in Data Spaces

### ISSUE THREAD

**Issue by ssteinbuss** [International-Data-Spaces-Association/IDSA-Rulebook#59]
Interoperability is a key aspect in Data Spaces and this should be described in the IDSA Rulebook, too.  
A first draft is available here 
[Dataspaces and Interoperability 2024 04 012.docx](https://github.com/International-Data-Spaces-Association/IDSA-Rulebook/files/15058841/Dataspaces.and.Interoperability.2024.04.012.docx)

**Comment by PeterKoen-MSFT** [comment]
just a reminder that we are looking for feedback. if there is no feedback we should probably move forward and publish the current version. We can still amend it later.

**Comment by gbrost** [comment]
Yes indeed. I will add some input next week, if that is ok for you.

**Comment by SilviaIDSA** [comment]
@PeterKoen-MSFT, sorry for late answer. I have reviewed the document and have minor comments. I don't know how to communicate them to you. Attached is the document with track changes and comments in case they are relevant to the chapter's improvement.
[Dataspaces.and.Interoperability.2024.04.012 SC.docx](https://github.com/user-attachments/files/15592503/Dataspaces.and.Interoperability.2024.04.012.SC.docx)

**Comment by PeterKoen-MSFT** [comment]
Hi Silvia,

Thanks for the comments in the file. The current feedback discussion is on the pull request for the md file. [https://github.com/International-Data-Spaces-Association/IDSA-Rulebook/pull/60/](https://github.com/International-Data-Spaces-Association/IDSA-Rulebook/pull/60/)

No need to replicate your comments there, I will read through the doc and work them in, just for future comments, let's try to keep them all in one place in the pull request.

Thanks,
Peter
