### ISSUE TITLE
"contributing_projects" links are wrong

### ISSUE THREAD

**Issue by VladimirAlexiev** [International-Data-Spaces-Association/IDSA-Rulebook#61]
https://docs.internationaldataspaces.org/ids-knowledgebase/v/idsa-rulebook/front-matter/contributing_projects has links like this:
https://docs.internationaldataspaces.org/ids-knowledgebase/v/idsa-rulebook/front-matter/www.midih.eu

Of course, these links are wrong and should be like https://www.midih.eu

**Comment by ssteinbuss** [comment]
Thanks for the hint, we will fix this immediately.
(class 1)
